name: "Feature Request"
description: "Suggest a new feature or enhancement for the Zowietek integration"
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Requests

        Thank you for taking the time to suggest an improvement! Before submitting:

        - Search [existing issues](https://github.com/troykelly/homeassistant-zowietek/issues?q=label%3Aenhancement) to check if your feature has already been requested
        - Consider if this is a ZowieBox firmware feature vs. an integration feature

        ---

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission Checklist"
      options:
        - label: "I have searched existing issues and this is not a duplicate"
          required: true
        - label: "This feature is related to the Home Assistant integration, not ZowieBox firmware itself"
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: "Feature Type"
      description: "What type of feature are you requesting?"
      options:
        - "New entity type (sensor, button, etc.)"
        - "New switch control"
        - "New service/action"
        - "Stream protocol support"
        - "Automation/trigger support"
        - "UI/Configuration improvement"
        - "Performance improvement"
        - "Documentation improvement"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "Is your feature request related to a problem? Please describe."
      placeholder: "I'm always frustrated when... / It would be helpful if... / Currently I have to manually..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the solution you'd like"
      placeholder: "I would like the integration to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Describe any alternative solutions or features you've considered"
      placeholder: "I tried using... / An alternative could be..."

  - type: dropdown
    id: priority
    attributes:
      label: "How important is this feature to you?"
      options:
        - "Nice to have - would improve my experience"
        - "Important - I need this for my use case"
        - "Critical - blocking my adoption of the integration"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: "Describe your specific use case for this feature"
      placeholder: "I want to create an automation that... / I need to display... / My setup includes..."
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: "Contribution"
      description: "Would you be willing to help implement this feature?"
      options:
        - label: "I would be willing to submit a PR for this feature"
        - label: "I can help test this feature"
        - label: "I can help document this feature"

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any other context, mockups, or examples about the feature request"
      placeholder: "Screenshots, links to similar implementations, etc."
